### ISSUE TITLE
DefaultChannelId: Failed to find a usable hardware address from the network interfaces; using random bytes: c8:7e:34:6b:c8:ff:72:8f

### ISSUE THREAD

**Issue by changjiashuai** [ReactiveX/RxNetty#512] opened 2016-06-02 10:25 UTC
version: RxNetty-0.4.16

DefaultChannelId: Failed to find a usable hardware address from the network interfaces; using random bytes: c8:7e:34:6b:c8:ff:72:8f

NioEventLoop: Selector.select() returned prematurely 512 times in a row; rebuilding selector.
NioEventLoop: Migrated 1 channel(s) to the new Selector.

death loop how to return error?

**Comment by NiteshKant** [comment] 2016-06-02 15:19
Which Java version are you using?
Can you also share the code you are using?

**Comment by changjiashuai** [comment] 2016-06-03 01:54
Java version 1.7

The issue just happened in OPPO X9000 mobile phone. And I find the [https://github.com/netty/netty/issues/3490](url) . the code can't share with you because it's private.

**Comment by NiteshKant** [comment] 2016-06-03 05:23
The issue is more than an year old and is fixed in the version RxNetty uses. Do you think the `Selector` returning prematurely is because of using random bytes for channel Id?

It does not look like an RxNetty issue, may be you should report to netty.

**Comment by changjiashuai** [comment] 2016-06-03 07:10
I think when the `Selector` returning prematurely is because of using random bytes for channel Id RxNetty should be throw a error not use random bytes  try to connect. Do you think?

**Comment by NiteshKant** [comment] 2016-06-08 17:07
I do not think the two things (random bytes for channel ID and selector returning prematurely) are related.

`ChannelId` is used internally by netty for bookkeeping and logging, it is not used by the java selector. Selector returning prematurely is due to a java nio bug which may be what is the case with the environment you are using.

**Comment by NiteshKant** [comment] 2016-06-25 23:33
I am closing this bug, I don't think it is an RxNetty issue (as explained above).

@changjiashuai let me know if you think otherwise.

**Closed as completed by NiteshKant** 2016-06-25 23:33 UTC
